# Generated by Django 5.1.5 on 2025-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verificacion_lab', models.CharField(max_length=50)),
                ('Est_situacion', models.CharField(max_length=50)),
                ('Acredi_ingresos', models.CharField(max_length=50)),
            ],
        ),
    ]
