# Generated by Django 5.1.5 on 2025-01-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formalidad', models.CharField(max_length=20, verbose_name='Formalidad')),
                ('gest_otorgamiento', models.CharField(max_length=20, verbose_name='Gestión de Otorgamiento')),
                ('depura_antecedent', models.CharField(max_length=20, verbose_name='Depuracion de Antecedentes')),
                ('ingreso_datos', models.CharField(max_length=20, verbose_name='Ingreso de Datos')),
            ],
        ),
        migrations.DeleteModel(
            name='Formalidad',
        ),
    ]
