# Generated by Django 5.1.5 on 2025-01-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
