# Generated by Django 5.1.5 on 2025-01-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('usuario', 'Analista de evaluación '), ('admin', 'Supervisor')], default='usuario', max_length=7),
        ),
    ]
