# Generated by Django 5.1.5 on 2025-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0007_alter_usuario_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
