# Generated by Django 5.1.5 on 2025-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilares',
            options={'verbose_name': 'Pilar', 'verbose_name_plural': 'Pilares'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='pilares',
            name='depura_antecedent',
            field=models.CharField(max_length=20, verbose_name='Depuración de Antecedentes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='roles',
            field=models.CharField(choices=[('usuario', 'Analista de evaluación'), ('supervisor', 'Supervisor')], default='usuario', max_length=10),
        ),
    ]
