# Generated by Django 5.1.5 on 2025-01-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0009_alter_pilares_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pilares',
        ),
    ]
