# Generated by Django 5.1.5 on 2025-01-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0010_delete_pilares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
