# Generated by Django 5.1.5 on 2025-01-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficha', '0011_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pilar1', models.CharField(max_length=100)),
                ('pilar2', models.CharField(max_length=100)),
                ('pilar3', models.CharField(max_length=100)),
                ('pilar4', models.CharField(max_length=100)),
            ],
        ),
    ]
