# Generated by Django 5.1.5 on 2025-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0012_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilares',
            old_name='pilar1',
            new_name='depuracion_de_antecedentes',
        ),
        migrations.RenameField(
            model_name='pilares',
            old_name='pilar2',
            new_name='formalidad',
        ),
        migrations.RenameField(
            model_name='pilares',
            old_name='pilar3',
            new_name='gestion_de_otorgamiento',
        ),
        migrations.RenameField(
            model_name='pilares',
            old_name='pilar4',
            new_name='ingreso_de_datos',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='name',
        ),
        migrations.AlterField(
            model_name='pilares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
