# Generated by Django 5.1.5 on 2025-01-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0013_rename_pilar1_pilares_depuracion_de_antecedentes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilares',
            old_name='depuracion_de_antecedentes',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='formalidad',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='gestion_de_otorgamiento',
        ),
        migrations.RemoveField(
            model_name='pilares',
            name='ingreso_de_datos',
        ),
    ]
