# Generated by Django 5.1.5 on 2025-02-03 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0014_rename_depuracion_de_antecedentes_pilares_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('rut', models.CharField(help_text='Formato: XXXXXXXX-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')])),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Errores_agravantes',
            fields=[
                ('id_base', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150)),
                ('tipo_error', models.CharField(max_length=150)),
                ('tipo_cliente', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_parametro', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='pilares',
            old_name='id',
            new_name='id_pilar',
        ),
    ]
