# Generated by Django 5.1.5 on 2025-02-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0015_cliente_errores_agravantes_parametro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
