# Generated by Django 5.1.5 on 2025-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0017_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejecutivos',
            fields=[
                ('rut_ejecutivo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_ejecutivo', models.CharField(max_length=100)),
                ('username_ejecutivo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oficina',
            fields=[
                ('cui', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_ofi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='oportunidad',
            fields=[
                ('id_oportunidad', models.AutoField(primary_key=True, serialize=False)),
                ('inconsistencia', models.CharField(max_length=200)),
                ('proceso_credito', models.CharField(max_length=20)),
                ('pauta_evaluacion', models.CharField(max_length=30)),
                ('prod_eval', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sucursal',
            fields=[
                ('cod_sucursal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_suc', models.CharField(max_length=50)),
                ('aprobador', models.CharField(max_length=30)),
                ('n_oportunidad', models.CharField(max_length=100)),
                ('cantidad_ejecutivo', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
    ]
