# Generated by Django 5.1.5 on 2025-02-05 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0019_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='cantidad_ejecutivo',
        ),
        migrations.AddField(
            model_name='errores_agravantes',
            name='nota',
            field=models.CharField(default='Sin nota', max_length=20),
        ),
        migrations.AddField(
            model_name='errores_agravantes',
            name='puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='anio_mes',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='canal',
            field=models.CharField(default='Sin dato', max_length=5),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='monto_solicitado',
            field=models.IntegerField(default=0, verbose_name='monto solicitado'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='username_ejecutivo',
            field=models.CharField(default='Sin Dato', max_length=20, verbose_name='Log Ejecutivo'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='cant_ejecutivo',
            field=models.CharField(default='Sin cantidad', max_length=5, verbose_name='Cantidad Ejecutivos'),
        ),
        migrations.AlterField(
            model_name='errores_agravantes',
            name='nombre_parametro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='errores_agravantes',
            name='tipo_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='errores_agravantes',
            name='tipo_error',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='cui',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre_ofi',
            field=models.CharField(max_length=50, verbose_name='Nombre Oficina'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='prod_eval',
            field=models.CharField(max_length=50, verbose_name='producto evaluado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='aprobador',
            field=models.CharField(max_length=30, verbose_name='Nombre aprobador'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='cod_sucursal',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='n_oportunidad',
            field=models.CharField(max_length=100, verbose_name='N° Oportunidad'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_suc',
            field=models.CharField(max_length=50, verbose_name='Nombre Sucursal'),
        ),
    ]
