# Generated by Django 5.1.5 on 2025-02-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0023_userprofile_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
