# Generated by Django 5.1.5 on 2025-02-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0024_userprofile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='static/img'),
        ),
    ]
