# Generated by Django 5.1.5 on 2025-02-11 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0026_alter_ejecutivos_rut_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecutivos',
            name='rut_ejecutivo',
            field=models.CharField(help_text='Formato: 20222777-X', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El RUT debe estar en formato XXXXXXXX-X', regex='^\\d{7,8}-[\\dkK]$')]),
        ),
    ]
