# Generated by Django 5.1.5 on 2025-02-12 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0027_alter_ejecutivos_rut_ejecutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='cui',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina'),
        ),
    ]
