# Generated by Django 5.1.5 on 2025-02-13 14:14

import django.db.models.deletion
import ficha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0028_oportunidad_cui'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ejecutivos',
            new_name='ejecutivo',
        ),
        migrations.RenameModel(
            old_name='Errores_agravantes',
            new_name='Errores_agravante',
        ),
        migrations.CreateModel(
            name='fitro_revision',
            fields=[
                ('id_filtro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejecutivo', models.CharField(max_length=40, verbose_name=ficha.models.ejecutivo)),
                ('username_ejecutivo', models.CharField(max_length=20, verbose_name=ficha.models.ejecutivo)),
                ('tipo_cliente', models.CharField(max_length=10, verbose_name=ficha.models.cliente)),
                ('nombre_suc', models.CharField(max_length=40, verbose_name=ficha.models.sucursal)),
                ('tipo_producto', models.CharField(max_length=20, verbose_name=ficha.models.cliente)),
                ('monto_solicitado', models.IntegerField(default=0, verbose_name='monto solicitado')),
                ('rut', models.CharField(max_length=10, verbose_name=ficha.models.cliente)),
                ('num_revision', models.CharField(max_length=10, verbose_name='Revisión N°: ')),
                ('cui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.oficina')),
            ],
        ),
    ]
