# Generated by Django 5.1.5 on 2025-02-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0029_rename_ejecutivos_ejecutivo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fitro_revision',
            new_name='filtro_revision',
        ),
    ]
